// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var $containers, child_count, filter_options, getRandomColor, renderChildren, renderPlaceholders;
    $containers = $(".ss-container");
    child_count = 30;
    filter_options = {
      minColumns: 3
    };
    $containers.shapeshift(filter_options);
    $(".controls .animations .switch").on("switch-change", function(e, data) {
      filter_options.animated = data.value;
      return $containers.shapeshift(filter_options);
    });
    $(".controls .dragndrop .switch").on("switch-change", function(e, data) {
      filter_options.enableDrag = data.value;
      filter_options.enableDrop = data.value;
      $containers.trigger('ss-destroy');
      return $containers.shapeshift(filter_options);
    });
    $(".controls .filtering button").on("click", function() {
      switch ($(this).data("option")) {
        case "hide":
          $containers.children(":visible").sort(function() {
            return Math.round(Math.random()) - 0.5;
          }).first().hide();
          break;
        default:
          $containers.children(":hidden").sort(function() {
            return Math.round(Math.random()) - 0.5;
          }).first().show();
      }
      return $containers.trigger("ss-rearrange");
    });
    $(".controls .placeholders button").on("click", function() {
      renderPlaceholders($(this).data("option"));
      return $containers.shapeshift(filter_options);
    });
    $containers.on("ss-arranged", function(e, selected) {
      var modifier;
      modifier = $(this).find(".ss-dragging")[0] ? 1 : 0;
      return $(this).children().each(function() {
        return $(this).find(".position div").text($(this).index() - modifier);
      });
    });
    $containers.on("ss-rearranged", function(e, selected) {
      console.log("----------------------------------------");
      console.log("This container:");
      console.log($(this));
      console.log("Has rearranged this item:");
      console.log($(selected));
      return console.log("Into this position:", $(selected).index());
    });
    $containers.on("ss-removed", function(e, selected) {
      console.log("----------------------------------------");
      console.log("This item:");
      console.log($(selected));
      console.log("Has been removed from this container:");
      return console.log($(this));
    });
    $containers.on("ss-added", function(e, selected) {
      console.log("----------------------------------------");
      console.log("This item:");
      console.log($(selected));
      console.log("Has been added to this container:");
      return console.log($(this));
    });
    $containers.on("ss-trashed", function(e, selected) {
      console.log("----------------------------------------");
      console.log("This item:");
      console.log($(selected));
      return console.log("Has been removed from the DOM");
    });
    return $containers.on("ss-drop-complete", function(e) {
      console.log("----------------------------------------");
      console.log("This container:");
      console.log($(this));
      return console.log("Has finished rearrangement after a drop.");
    });
  });

}).call(this);
